PHONY_TARGETS += help

help:
	@echo "BoxLite Build Commands:"
	@echo ""
	@echo "  Setup:"
	@echo "    make setup          - Install dependencies and bootstrap git hooks (best-effort)"
	@echo ""
	@echo "  Cleanup:"
	@echo "    make clean          - Clean everything (cargo, SDKs, .venv, temp files)"
	@echo "    make clean:dist     - Clean only SDK distribution artifacts"
	@echo ""
	@echo "  Code Quality:"
	@echo "    make fmt                   - Format Rust/Python/Node/C code"
	@echo "    make fmt:check             - Check formatting for Rust/Python/Node/C"
	@echo "    make lint                  - Run lint checks (Rust/Python/Node/C)"
	@echo "    make lint:fix              - Auto-fix via formatters + Python lint fixes, then re-check"
	@echo "    make clippy                - Run Rust clippy checks (includes macOS cross-target guest)"
	@echo ""
	@echo "  Build:"
	@echo "    make cli            - Build the CLI (boxlite command)"
	@echo "    make guest          - Build the guest binary (cross-compile for VM)"
	@echo "    make runtime        - Build runtime artifacts (release)"
	@echo "    make runtime-debug  - Build runtime artifacts (debug)"
	@echo "    make skillbox-image - Build SkillBox Docker image (APT_SOURCE=mirrors.aliyun.com for China)"
	@echo ""
	@echo "  Testing (strict full-matrix default):"
	@echo "    make test                   - Run full test matrix (same as make test:all)"
	@echo "    make test:all               - Run full test matrix (unit + integration)"
	@echo "    make test:unit              - Run all unit suites"
	@echo "    make test:integration       - Run all integration suites"
	@echo "    make test:unit:core         - Run Rust/FFI unit suites"
	@echo "    make test:integration:core  - Run core integration suites (Rust + CLI)"
	@echo "    make test:unit:sdk          - Run SDK unit suites (Python + Node)"
	@echo "    make test:integration:sdk   - Run SDK integration suites (Python + C)"
	@echo "    make test:unit:rust         - Run Rust unit tests (nextest when available)"
	@echo "    make test:warm-cache:rust   - Pre-warm Rust integration image cache"
	@echo "    make test:integration:rust  - Run Rust integration tests (requires VM)"
	@echo "    make test:unit:ffi          - Run BoxLite FFI unit tests"
	@echo "    make test:integration:cli   - Run CLI integration tests"
	@echo "    make test:unit:python       - Run Python SDK unit tests"
	@echo "    make test:integration:python - Run Python SDK integration tests"
	@echo "    make test:all:python        - Run Python SDK unit + integration tests"
	@echo "    make test:unit:node         - Run Node.js SDK unit tests"
	@echo "    make test:all:c             - Run C SDK test suite (CTest)"
	@echo ""
	@echo "  Coverage:"
	@echo "    make coverage              - Generate HTML coverage report (unit tests)"
	@echo "    make coverage:lcov         - Generate LCOV output for CI upload"
	@echo "    make coverage:integration  - Generate coverage for Rust integration tests"
	@echo ""
	@echo "  Local Development:"
	@echo "    make dev:python     - Build and install Python SDK locally (debug mode)"
	@echo "    make dev:c          - Package C SDK artifacts for local testing"
	@echo "    make dev:node       - Build and link Node.js SDK locally (debug mode)"
	@echo ""
	@echo "  Distribution:"
	@echo "    make dist:python    - Build portable wheel with cibuildwheel"
	@echo "    make dist:c         - Package C runtime artifacts"
	@echo "    make dist:node      - Build npm package with napi-rs"
	@echo "    make package        - Alias for make dist:c"
	@echo ""
	@echo "Platform: $$(uname) ($$(uname -m))"
	@echo ""
